language: go

go:
  - 1.11.x
  - master

env:
  - GIN_MODE="test" GO111MODULE=on

cache:
  directories:
    - $HOME/gopath/src/

before_install:
  - go mod tidy
  - go get github.com/swaggo/swag/cmd/swag
  - swag init

script:
  - make cov

after_success:
  - bash <(curl -s https://codecov.io/bash)